CREATE TABLE CAST_ERROR
(
    ID                  BIGINT       NOT NULL AUTO_INCREMENT,
    SOURCE              VARCHAR(200) NOT NULL,
    DEVICE_MODEL        VARCHAR(50)  NOT NULL,
    DEVICE_MANUFACTURER VARCHAR(50)  NOT NULL,
    DEVICE_BRAND        VARCHAR(50)  NOT NULL,
    OS_VERSION          VARCHAR(10)  NOT NULL,
    APP_VERSION         VARCHAR(10)  NOT NULL,
    CAST_DEVICE_NAME    VARCHAR(50)  NOT NULL,
    ERROR               TEXT,
    REPORTED_AT         DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
);
