CREATE TABLE PROFILE_IMAGE
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    FILE_NAME VARCHAR(250) NOT NULL,
    ADDED_AT  DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
);
