CREATE TABLE SUBTITLE
(
    ID                    BIGINT       NOT NULL AUTO_INCREMENT,
    ASSOCIATED_WITH_VIDEO VARCHAR(250) NOT NULL,
    LANGUAGE              VARCHAR(16)  NOT NULL,
    SUBTITLE              VARCHAR(250) NOT NULL,
    COLLECTION            VARCHAR(250) NOT NULL,
    FORMAT                VARCHAR(12)  NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT uq_subtitle_video_language_format UNIQUE (ASSOCIATED_WITH_VIDEO, LANGUAGE, FORMAT)
)