CREATE TABLE SUMMARY
(
    ID          BIGINT      NOT NULL AUTO_INCREMENT,
    DESCRIPTION TEXT        NOT NULL,
    LANGUAGE    VARCHAR(16) NOT NULL,
    CATALOG_ID  INT         NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT uq_summary_language_cid UNIQUE (LANGUAGE, CATALOG_ID)
);