CREATE TABLE TITLES
(
    ID               BIGINT          NOT NULL AUTO_INCREMENT,
    MASTER_TITLE      VARCHAR(250) NOT NULL,
    ALTERNATIVE_TITLE VARCHAR(250) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT uq_titles_master_alternative UNIQUE (MASTER_TITLE, ALTERNATIVE_TITLE)
);
