CREATE TABLE USERS
(
    ID      BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID CHAR(36)     NOT NULL,
    NAME    VARCHAR(50)  NOT NULL,
    IMAGE   VARCHAR(200) NOT NULL,
    CONSTRAINT uq_users_name UNIQUE (NAME)
);
