CREATE TABLE MEDIA_VIDEO_DATA
(
    ID           BIGINT       NOT NULL AUTO_INCREMENT,
    SOURCE       VARCHAR(200) NOT NULL,
    CODEC        VARCHAR(12)  NOT NULL,
    PIXEL_FORMAT VARCHAR(12)  NOT NULL,
    COLOR_SPACE  VARCHAR(8),
    PRIMARY KEY (ID),
    CONSTRAINT uq_media_video_data_source UNIQUE (SOURCE)
);
