CREATE TABLE MEDIA_DATA_AUDIO
(
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    SOURCE      VARCHAR(200) NOT NULL,
    CODEC       VARCHAR(12)  NOT NULL,
    CHANNELS    INT,
    SAMPLE_RATE INT,
    LAYOUT      VARCHAR(8),
    LANGUAGE    VARCHAR(6)   NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT uq_media_data_audio_source UNIQUE (SOURCE)
);
