CREATE TABLE TOKENS
(
    ID             BIGINT      NOT NULL AUTO_INCREMENT,
    TOKEN_ID       VARCHAR(36) NOT NULL,
    TOKEN          TEXT        NOT NULL,
    CREATED_AT     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    REVOKED        BOOLEAN     NOT NULL DEFAULT FALSE,
    REVOKED_REASON TEXT,
    PRIMARY KEY (ID),
    CONSTRAINT uq_tokens_tokenid UNIQUE (TOKEN_ID)
);
