CREATE TABLE DELEGATED_AUTHENTICATION
(
    ID          BIGINT          NOT NULL AUTO_INCREMENT,
    PIN         VARCHAR(8)   NOT NULL,
    REQUESTER_ID CHAR(64)     NOT NULL,
    DEVICE_INFO  VARCHAR(256) NOT NULL,
    CREATED_AT     DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    EXPIRES_AT     DATETIME(6)  NOT NULL,
    PERMITTED   BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSUMED    BOOLEAN      NOT NULL DEFAULT FALSE,
    METHOD      VARCHAR(3)   NOT NULL,
    IP_ADDRESS   VARCHAR(39),
    PRIMARY KEY (ID),
    CONSTRAINT uq_delegated_authentication_pin UNIQUE (PIN)
);