CREATE TABLE USERS
(
    ID      BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID CHAR(36)     NOT NULL,
    NAME    VARCHAR(50)  NOT NULL,
    IMAGE   VARCHAR(200) NOT NULL,
    CONSTRAINT uq_users_name UNIQUE (NAME)
);


CREATE TABLE VIDEO
(
    ID       BIGINT       NOT NULL AUTO_INCREMENT,
    FILE     VARCHAR(500) NOT NULL,
    DURATION INT          NULL,
    ADDED_AT TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE SUBTITLE
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    VIDEO_ID  BIGINT       NOT NULL,
    LANGUAGE  VARCHAR(20)  NOT NULL,
    FORMAT    VARCHAR(20)  NOT NULL,
    FILE      VARCHAR(500) NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT fk_subtitle_video
        FOREIGN KEY (VIDEO_ID)
            REFERENCES VIDEO(ID)
            ON DELETE CASCADE,

    CONSTRAINT uq_subtitle_video_language_format
        UNIQUE (VIDEO_ID, LANGUAGE, FORMAT)
);

CREATE TABLE PROGRESS
(
    ID        BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID   BIGINT NOT NULL,
    VIDEO_ID  BIGINT NOT NULL,
    POSITION  BIGINT    NOT NULL DEFAULT 0,
    PLAYED    DATETIME(6),

    PRIMARY KEY (ID),

    CONSTRAINT fk_progress_user
        FOREIGN KEY (USER_ID)
            REFERENCES USERS(ID)
            ON DELETE CASCADE,

    CONSTRAINT fk_progress_video
        FOREIGN KEY (VIDEO_ID)
            REFERENCES VIDEO(ID)
            ON DELETE CASCADE,

    CONSTRAINT uq_progress_user_video
        UNIQUE (USER_ID, VIDEO_ID)
);

CREATE TABLE CATALOG
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    STORE     VARCHAR(500) NOT NULL,
    COVER     VARCHAR(500),
    TYPE      VARCHAR(10)  NOT NULL,
    ADDED_AT  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (ID)
);

CREATE TABLE MOVIE
(
    ID         BIGINT NOT NULL AUTO_INCREMENT,
    CATALOG_ID BIGINT NOT NULL,
    VIDEO_ID   BIGINT NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT fk_movie_catalog
        FOREIGN KEY (CATALOG_ID)
            REFERENCES CATALOG(ID)
            ON DELETE CASCADE,

    CONSTRAINT fk_movie_video
        FOREIGN KEY (VIDEO_ID)
            REFERENCES VIDEO(ID)
);

CREATE TABLE SERIE
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    CATALOG_ID BIGINT      NOT NULL,
    EPISODE   INT          NOT NULL,
    SEASON    INT          NOT NULL,
    TITLE     VARCHAR(500),
    VIDEO_ID  BIGINT       NOT NULL,
    ADDED_AT  DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (ID),

    CONSTRAINT fk_serie_catalog
        FOREIGN KEY (CATALOG_ID)
            REFERENCES CATALOG(ID)
            ON DELETE CASCADE,

    CONSTRAINT fk_serie_video
        FOREIGN KEY (VIDEO_ID)
            REFERENCES VIDEO(ID),

    CONSTRAINT uq_serie_episode_season_catalog
        UNIQUE (CATALOG_ID, EPISODE, SEASON),

    CONSTRAINT uq_serie_video
        UNIQUE (VIDEO_ID)
);

CREATE TABLE CATALOG_TITLE
(
    ID         BIGINT       NOT NULL AUTO_INCREMENT,
    CATALOG_ID BIGINT       NOT NULL,
    TITLE      VARCHAR(500) NOT NULL,
    LANGUAGE   VARCHAR(16)  NOT NULL,
    PREFERRED  BOOLEAN      NOT NULL DEFAULT FALSE,

    PRIMARY KEY (ID),

    CONSTRAINT fk_catalog_title_catalog
        FOREIGN KEY (CATALOG_ID)
            REFERENCES CATALOG(ID)
            ON DELETE CASCADE,

    CONSTRAINT uq_catalog_title
        UNIQUE (CATALOG_ID, TITLE, LANGUAGE)
);

CREATE TABLE SUMMARY
(
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    CATALOG_ID  BIGINT       NOT NULL,
    DESCRIPTION TEXT         NOT NULL,
    LANGUAGE    VARCHAR(16)  NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT fk_summary_catalog
        FOREIGN KEY (CATALOG_ID)
            REFERENCES CATALOG(ID)
            ON DELETE CASCADE,

    CONSTRAINT uq_summary_catalog_language
        UNIQUE (CATALOG_ID, LANGUAGE)
);

CREATE TABLE FAVORITES
(
    ID         BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID    BIGINT NOT NULL,
    CATALOG_ID BIGINT NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT fk_favorites_user
        FOREIGN KEY (USER_ID)
            REFERENCES USERS(ID)
            ON DELETE CASCADE,

    CONSTRAINT fk_favorites_catalog
        FOREIGN KEY (CATALOG_ID)
            REFERENCES CATALOG(ID)
            ON DELETE CASCADE,

    CONSTRAINT uq_favorites_user_catalog
        UNIQUE (USER_ID, CATALOG_ID)
);

CREATE TABLE CONTINUE_WATCH
(
    ID         BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID    BIGINT NOT NULL,
    CATALOG_ID BIGINT NOT NULL,
    HIDE       BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (ID),

    CONSTRAINT fk_continue_watch_user
        FOREIGN KEY (USER_ID)
            REFERENCES USERS(ID)
            ON DELETE CASCADE,

    CONSTRAINT fk_continue_watch_catalog
        FOREIGN KEY (CATALOG_ID)
            REFERENCES CATALOG(ID)
            ON DELETE CASCADE,

    CONSTRAINT uq_continue_watch_user_catalog
        UNIQUE (USER_ID, CATALOG_ID)
);

CREATE TABLE GENRE
(
    ID    BIGINT      NOT NULL AUTO_INCREMENT,
    GENRE VARCHAR(50) NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT uq_genre_genre
        UNIQUE (GENRE)
);

CREATE TABLE CATALOG_GENRE
(
    CATALOG_ID BIGINT NOT NULL,
    GENRE_ID   BIGINT NOT NULL,

    PRIMARY KEY (CATALOG_ID, GENRE_ID),

    CONSTRAINT fk_catalog_genre_catalog
        FOREIGN KEY (CATALOG_ID)
            REFERENCES CATALOG(ID)
            ON DELETE CASCADE,

    CONSTRAINT fk_catalog_genre_genre
        FOREIGN KEY (GENRE_ID)
            REFERENCES GENRE(ID)
            ON DELETE CASCADE
);