CREATE TABLE REGISTERED_DEVICES
(
    ID                       BIGINT       NOT NULL AUTO_INCREMENT,
    DEVICE_ID                VARCHAR(256) NOT NULL,
    APPLICATION_PACKAGE_NAME VARCHAR(32)  NOT NULL,
    OS_VERSION               VARCHAR(28)  NOT NULL,
    OS_PLATFORM              VARCHAR(28)  NOT NULL,
    REGISTERED_AT            DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    LAST_SEEN_AT             DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
);