CREATE TABLE CATALOG
(
    ID         BIGINT       NOT NULL AUTO_INCREMENT,
    TITLE      VARCHAR(255) NOT NULL,
    COVER      VARCHAR(255),
    TYPE       VARCHAR(50)  NOT NULL,
    COLLECTION VARCHAR(255) NOT NULL,
    IID        INT,
    GENRES     VARCHAR(24),
    ADDED_AT   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT uq_catalog_title_type UNIQUE (TITLE, TYPE)
);