CREATE TABLE CONTINUE_WATCH
(
    ID         BIGINT       NOT NULL AUTO_INCREMENT,
    USER_ID    CHAR(36)     NOT NULL,
    TYPE       VARCHAR(10)  NOT NULL,
    TITLE      VARCHAR(250) NOT NULL,
    COLLECTION VARCHAR(250),
    HIDE       BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ID)
)
