CREATE TABLE FAVORITES
(
    ID        BIGINT      NOT NULL AUTO_INCREMENT,
    USER_ID    CHAR(36) NOT NULL,
    CATALOG_ID INT      NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT uq_favorites_user_catalog UNIQUE (USER_ID, CATALOG_ID)
);