CREATE TABLE SERIE
(
    ID         BIGINT       NOT NULL AUTO_INCREMENT,
    TITLE      VARCHAR(250),
    EPISODE    INT          NOT NULL,
    SEASON     INT          NOT NULL,
    COLLECTION VARCHAR(250) NOT NULL,
    VIDEO      VARCHAR(500) NOT NULL,
    ADDED_AT   DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    CONSTRAINT uq_serie_episode_season_collection UNIQUE (EPISODE, SEASON, COLLECTION),
    CONSTRAINT uq_serie_video UNIQUE (video)
)
