spring:
  output:
    ansi:
      enabled: ALWAYS
  flyway:
    enabled: true
    locations: classpath:flyway
    baseline-on-migrate: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /open/swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true

logging:
  level:
    org:
      springframework:
        web:
          socket:
            config:
              WebSocketMessageBrokerStats: WARN
